[versions]
kotlin = "2.3.10"
ksp = "2.3.5"

[plugins]
kotlin-jvm      = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
google-ksp      = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
bom-junit5      = { module = "org.junit:junit-bom", version = "5.14.2" }

google-kspApi   = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinpoet      = { module = "com.squareup:kotlinpoet", version = "2.2.0" }

junit-jupiter   = { module = "org.junit.jupiter:junit-jupiter" }
junit-launcher  = { module = "org.junit.platform:junit-platform-launcher" }
assertj         = { module = "org.assertj:assertj-core", version = "3.27.6" }
